### PR TITLE
net-proxy/yass: add 1.8.0 drop 1.6.5

### PR DESCRIPTION
**Pull request by Chilledheart**

### CODE REVIEW

**Comment by Chilledheart** [comment]
btw yass has support for arm and mips64el but I can't find a chance to verify it if it works. Add these two targets as unstable.

image

https://github.com/Chilledheart/yass/actions/runs/8355366222

**Comment by liangyongxiang** [comment]
I have the 3a4000 hardware, but I loaned it to someone else.
I can test it out sometime.

**Comment by Chilledheart** [comment]
Great. I am already able to run and pass unittest under qemu emulation. It will be really nice if we can test it on a real machine.

**Comment by Chilledheart** [comment]
FYI I managed to add a qemu emulation bot for loongarch64

https://github.com/Chilledheart/yass/actions/runs/8585755255/job/23527492500

image

**Pull request merged**
